package compiler;

public class Selectionset
{
    public static String[] first_DEFS;
    public static String[] first_INITOPT;
    public static String[] first_SST1;
    public static String[] first_INIT1;
    public static String[] first_INIT2;
    public static String[] first_CONSTOPT;
    public static String[] first_ARRINITOPT1;
    public static String[] first_ARRINIT1;
    public static String[] first_VAL2;
    public static String[] first_VAL;
    public static String[] first_TWODARRINITOPT1;
    public static String[] first_TWODARRINIT;
    public static String[] first_TWODARRINIT1;
    public static String[] first_ARRINIT;
    public static String[] first_ARR;
    public static String[] first_SST2;
    public static String[] first_SST4;
    public static String[] first_SST3;
    public static String[] first_SST5;
    public static String[] first_SST6;
    public static String[] first_ARRINITOPT;
    public static String[] first_TWODARRINITOPT;
    public static String[] first_FUNCSST;
    public static String[] first_FUNCMST;
    public static String[] first_CLASSSST10;
    public static String[] first_CLASSSST1;
    public static String[] first_AM;
    public static String[] first_CLASSSST2;
    public static String[] first_CLASSSST9;
    public static String[] first_CLASSSST8;
    public static String[] first_CLASSSST3;
    public static String[] first_CLASSSST7;
    public static String[] first_CLASSSST4;
    public static String[] first_CLASSSST6;
    public static String[] first_CLASSSST5;
    public static String[] first_DECLIST;
    public static String[] first_SQBRACK;
    public static String[] first_ROCONST;
    public static String[] first_CLASS_SST;
    public static String[] first_SST;
    public static String[] first_LOOPSST;
    public static String[] first_LOOPMST;
    public static String[] first_WHILEST;
    public static String[] first_DOWHILEST;
    public static String[] first_ASSIGNOPT;
    public static String[] first_FORST;
    public static String[] first_LOOPBODY;
    public static String[] first_C1;
    public static String[] first_DECFB;
    public static String[] first_C2;
    public static String[] first_C3;
    public static String[] first_C4;
    public static String[] first_C5;
    public static String[] first_ASSST;
    public static String[] first_ASSIGNST;
    public static String[] first_ASSIGN1;
    public static String[] first_ASSIGN2;
    public static String[] first_ASSIGN;
    public static String[] first_IFELSE;
    public static String[] first_ELSE;
    public static String[] first_OEOPT;
    public static String[] first_PARAM;
    public static String[] first_DTOPT;
    public static String[] first_MDM;
    public static String[] first_PM;
    public static String[] first_AOP;
    public static String[] first_ROP;
    public static String[] first_ID;
    public static String[] first_DOT;
    public static String[] first_OE;
    public static String[] first_ID2;
    public static String[] first_IDM;
    public static String[] first_ID1;
    public static String[] first_IDS;
    public static String[] first_IDOPT;
    public static String[] first_FUNCBODY;
    public static String[] first_TRY;
    public static String[] first_INCORDEC;
    public static String[] first_INCORDECOPT;
    public static String[] first_PARAM1;
    public static String[] first_F1;
    public static String[] first_F;
    public static String[] first_T1;
    public static String[] first_T;
    public static String[] first_E1;
    public static String[] first_E;
    public static String[] first_RE1;
    public static String[] first_RE;
    public static String[] first_AE1;
    public static String[] first_AE;
    public static String[] first_OE1;
    public static String[] first_SQBRACKOPT;
    public static String[] first_OBJST;
    public static String[] first_ARGLIST1;
    public static String[] first_ARGLST;
    public static String[] first_SUPERTHIS;
    public static String[] first_INHERITOPT1;
    public static String[] first_INHERITOPT;
    public static String[] first_CLASSBODY;
    public static String[] first_CLASSSIG;
    public static String[] first_CLASSST;
    public static String[] first_STATICOPT;
    public static String[] first_AMOPT;
    public static String[] first_PARAM2;
    public static String[] first_PARAM3;
    public static String[] first_SQBRACKC;
    public static String[] first_PARAMLST2;
    public static String[] first_PARAMLST3;
    public static String[] first_INIT;
    public static String[] first_PARAMINIT;
    public static String[] first_PARAMLST;
    public static String[] follow_AMOPT;
    public static String[] follow_STATICOPT;
    public static String[] follow_INIT2;
    public static String[] follow_INITOPT;
    public static String[] follow_CONSTOPT;
    public static String[] follow_ARRINITOPT;
    public static String[] follow_VAL2;
    public static String[] follow_OEOPT;
    public static String[] follow_TWODARRINITOPT;
    public static String[] follow_ARR;
    public static String[] follow_INHERITOPT1;
    public static String[] follow_FUNCMST;
    public static String[] follow_CLASSBODY;
    public static String[] follow_LOOPMST;
    public static String[] follow_ASSIGNOPT;
    public static String[] follow_C3;
    public static String[] follow_C5;
    public static String[] follow_ASSIGN2;
    public static String[] follow_ELSE;
    public static String[] follow_PARAM;
    public static String[] follow_PARAMLST;
    public static String[] follow_PARAMLST3;
    public static String[] follow_SQBRACKOPT;
    public static String[] follow_PARAM1;
    public static String[] follow_PARAM3;
    public static String[] follow_INHERITOPT;
    public static String[] follow_ARGLST;
    public static String[] follow_ARGLIST1;
    public static String[] follow_OE1;
    public static String[] follow_AE1;
    public static String[] follow_RE1;
    public static String[] follow_E1;
    public static String[] follow_T1;
    public static String[] follow_INCORDECOPT;
    public static String[] follow_IDOPT;
    public static String[] follow_DOT;
    public static String[] follow_C2;
    public static String[] follow_PARAMINIT;
    public static String[] follow_F1;
    public static String[] follow_IDM;
    public static String[] follow_ID1;
    
    static {
        Selectionset.first_DEFS = new String[] { "class", "public", "private", "protected", "static" };
        Selectionset.first_INITOPT = new String[] { "=" };
        Selectionset.first_SST1 = new String[] { "(", "++", "--", "=", "+=", "-=", "*=", "/=", "%=" };
        Selectionset.first_INIT1 = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_INIT2 = new String[] { "=" };
        Selectionset.first_CONSTOPT = new String[] { "const" };
        Selectionset.first_ARRINITOPT1 = new String[] { "{", "this", "id" };
        Selectionset.first_ARRINIT1 = new String[] { "}", "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_VAL2 = new String[] { "," };
        Selectionset.first_VAL = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_TWODARRINITOPT1 = new String[] { "{", "this", "id" };
        Selectionset.first_TWODARRINIT = new String[] { "{" };
        Selectionset.first_TWODARRINIT1 = new String[] { "}", "{" };
        Selectionset.first_ARRINIT = new String[] { "{" };
        Selectionset.first_ARR = new String[] { "," };
        Selectionset.first_SST2 = new String[] { ".", "(", "[", "id", "++", "--", "=", "+=", "-=", "*=", "/=", "%=" };
        Selectionset.first_SST4 = new String[] { ";", "." };
        Selectionset.first_SST3 = new String[] { "]", ",", "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_SST5 = new String[] { "[", "id" };
        Selectionset.first_SST6 = new String[] { "]", "," };
        Selectionset.first_ARRINITOPT = new String[] { "=" };
        Selectionset.first_TWODARRINITOPT = new String[] { "=" };
        Selectionset.first_FUNCSST = new String[] { ";", "return", "dt", "const", "id", "this", "try", "while", "for", "if", "do", "++", "--" };
        Selectionset.first_FUNCMST = Selectionset.first_FUNCSST;
        Selectionset.first_CLASSSST10 = new String[] { "id", "final", "dt", "readonly", "const" };
        Selectionset.first_CLASSSST1 = new String[] { "(", "." };
        Selectionset.first_AM = new String[] { "public", "private" };
        Selectionset.first_CLASSSST2 = new String[] { "final", "id", "static", "dt", "readonly", "const" };
        Selectionset.first_CLASSSST9 = new String[] { "(", "id" };
        Selectionset.first_CLASSSST8 = new String[] { "(", ";", ",", "=" };
        Selectionset.first_CLASSSST3 = new String[] { "final", "dt", "readonly", "const", "id" };
        Selectionset.first_CLASSSST7 = new String[] { "dt", "id" };
        Selectionset.first_CLASSSST4 = new String[] { "final", "dt", "readonly", "const", "id" };
        Selectionset.first_CLASSSST6 = new String[] { "id", "[" };
        Selectionset.first_CLASSSST5 = new String[] { "dt", "id" };
        Selectionset.first_DECLIST = new String[] { ";", "," };
        Selectionset.first_SQBRACK = new String[] { "[" };
        Selectionset.first_ROCONST = new String[] { "readonly", "const" };
        Selectionset.first_CLASS_SST = new String[] { "super", "static", "protected", "public", "private" };
        Selectionset.first_SST = new String[] { ";", "return", "dt", "const", "id", "this", "while", "for", "if", "do", "++", "--" };
        Selectionset.first_LOOPSST = new String[] { "break", "continue", ";", "return", "dt", "const", "id", "this", "try", "while", "for", "if", "do", "++", "--" };
        Selectionset.first_LOOPMST = new String[] { "break", "continue", ";", "return", "dt", "const", "id", "this", "try", "while", "for", "if", "do", "++", "--" };
        Selectionset.first_WHILEST = new String[] { "while" };
        Selectionset.first_DOWHILEST = new String[] { "do" };
        Selectionset.first_ASSIGNOPT = new String[] { ";" };
        Selectionset.first_FORST = new String[] { "for" };
        Selectionset.first_LOOPBODY = new String[] { "{", "break", "continue", ";", "return", "dt", "const", "id", "this", "try", "while", "for", "if", "do", "++", "--" };
        Selectionset.first_C1 = new String[] { ";", "dt", "const", "this", "id" };
        Selectionset.first_DECFB = new String[] { "dt", "const" };
        Selectionset.first_C2 = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_C3 = new String[] { "this", "++", "--", "id" };
        Selectionset.first_C4 = new String[] { "this", "++", "--", "id" };
        Selectionset.first_C5 = new String[] { "++", "--", "=", "+=", "-=", "*=", "/=", "%=" };
        Selectionset.first_ASSST = new String[] { "this", "id" };
        Selectionset.first_ASSIGNST = new String[] { "this", "id" };
        Selectionset.first_ASSIGN1 = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_ASSIGN2 = new String[] { "=", "+=", "-=", "*=", "/=", "%=" };
        Selectionset.first_ASSIGN = new String[] { "=", "+=", "-=", "*=", "/=", "%=" };
        Selectionset.first_IFELSE = new String[] { "if" };
        Selectionset.first_ELSE = new String[] { "else" };
        Selectionset.first_OEOPT = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_PARAM = new String[] { "dt", "id" };
        Selectionset.first_DTOPT = new String[] { "dt", "id" };
        Selectionset.first_MDM = new String[] { "*", "/", "%" };
        Selectionset.first_PM = new String[] { "+", "-" };
        Selectionset.first_AOP = new String[] { "=", "+=", "-=", "*=", "/=", "%=" };
        Selectionset.first_ROP = new String[] { "<", ">", "==", "!=", "<=", ">=" };
        Selectionset.first_ID = new String[] { "id" };
        Selectionset.first_DOT = new String[] { "." };
        Selectionset.first_OE = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_ID2 = new String[] { "]", "," };
        Selectionset.first_IDM = new String[] { "[", "." };
        Selectionset.first_ID1 = new String[] { "[", "." };
        Selectionset.first_IDS = new String[] { "this", "id" };
        Selectionset.first_IDOPT = new String[] { "id" };
        Selectionset.first_FUNCBODY = new String[] { "{" };
        Selectionset.first_TRY = new String[] { "try" };
        Selectionset.first_INCORDEC = new String[] { "++", "--" };
        Selectionset.first_INCORDECOPT = new String[] { "++", "--" };
        Selectionset.first_PARAM1 = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_F1 = new String[] { "(", "++", "--" };
        Selectionset.first_F = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_T1 = new String[] { "*", "/", "%" };
        Selectionset.first_T = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_E1 = new String[] { "+", "-" };
        Selectionset.first_E = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_RE1 = new String[] { "<", ">", "==", "!=", "<=", ">=" };
        Selectionset.first_RE = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_AE1 = new String[] { "&" };
        Selectionset.first_AE = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_OE1 = new String[] { "|" };
        Selectionset.first_SQBRACKOPT = new String[] { "[" };
        Selectionset.first_OBJST = new String[] { "id" };
        Selectionset.first_ARGLIST1 = new String[] { "," };
        Selectionset.first_ARGLST = new String[] { "dt" };
        Selectionset.first_SUPERTHIS = new String[] { "super", "this" };
        Selectionset.first_INHERITOPT1 = new String[] { "inherit" };
        Selectionset.first_INHERITOPT = new String[] { "inherit" };
        Selectionset.first_CLASSBODY = new String[] { "super", "static", "protected", "public", "private" };
        Selectionset.first_CLASSSIG = new String[] { "class", "public", "private", "protected", "static" };
        Selectionset.first_CLASSST = new String[] { "class", "public", "private", "protected", "static" };
        Selectionset.first_STATICOPT = new String[] { "static" };
        Selectionset.first_AMOPT = new String[] { "public", "private", "protected" };
        Selectionset.first_PARAM2 = new String[] { "literal", "!", "(", "++", "--", "this", "id" };
        Selectionset.first_PARAM3 = new String[] { "," };
        Selectionset.first_SQBRACKC = new String[] { "]", "," };
        Selectionset.first_PARAMLST2 = new String[] { "," };
        Selectionset.first_PARAMLST3 = new String[] { "," };
        Selectionset.first_INIT = new String[] { "=" };
        Selectionset.first_PARAMINIT = new String[] { ",", "=" };
        Selectionset.first_PARAMLST = new String[] { "," };
        Selectionset.follow_AMOPT = new String[] { "static", "class" };
        Selectionset.follow_STATICOPT = new String[] { "final", "dt", "readonly", "const", "id", "class" };
        Selectionset.follow_INIT2 = new String[] { ")", ";", "," };
        Selectionset.follow_INITOPT = new String[] { ";", "," };
        Selectionset.follow_CONSTOPT = new String[] { "dt" };
        Selectionset.follow_ARRINITOPT = new String[] { ";" };
        Selectionset.follow_VAL2 = new String[] { "}" };
        Selectionset.follow_OEOPT = new String[] { ";", ",", "]", ")" };
        Selectionset.follow_TWODARRINITOPT = new String[] { ";" };
        Selectionset.follow_ARR = new String[] { "}" };
        Selectionset.follow_INHERITOPT1 = new String[] { "{" };
        Selectionset.follow_FUNCMST = new String[] { "}" };
        Selectionset.follow_CLASSBODY = new String[] { "}", "void" };
        Selectionset.follow_LOOPMST = new String[] { "}" };
        Selectionset.follow_ASSIGNOPT = new String[] { ")" };
        Selectionset.follow_C3 = new String[] { ")" };
        Selectionset.follow_C5 = new String[] { ")" };
        Selectionset.follow_ASSIGN2 = new String[] { ")", ";" };
        Selectionset.follow_ELSE = new String[] { "break", "continue", "}", ";", "return", "dt", "const", "id", "this", "try", "while", "for", "if", "do", "++", "--" };
        Selectionset.follow_PARAM = new String[] { ")" };
        Selectionset.follow_PARAMLST = new String[] { ")" };
        Selectionset.follow_PARAMLST3 = new String[] { ")" };
        Selectionset.follow_SQBRACKOPT = new String[] { "id" };
        Selectionset.follow_PARAM1 = new String[] { ")" };
        Selectionset.follow_PARAM3 = new String[] { ")" };
        Selectionset.follow_INHERITOPT = new String[] { "{" };
        Selectionset.follow_ARGLST = new String[] { ")" };
        Selectionset.follow_ARGLIST1 = new String[] { ")" };
        Selectionset.follow_OE1 = new String[] { "}", ";", "=", "+=", "-=", "*=", "/=", "%=", ")", ",", "]" };
        Selectionset.follow_AE1 = new String[] { "|", "}", ";", "=", "+=", "-=", "*=", "/=", "%=", ")", ",", "]" };
        Selectionset.follow_RE1 = new String[] { "&", "|", "}", ";", "=", "+=", "-=", "*=", "/=", "%=", ")", ",", "]" };
        Selectionset.follow_E1 = new String[] { "<", ">", "==", "!=", "<=", ">=", "&", "|", "}", ";", "=", "+=", "-=", "*=", "/=", "%=", ")", ",", "]" };
        Selectionset.follow_T1 = new String[] { "+", "-", "<", ">", "==", "!=", "<=", ">=", "&", "|", "}", ";", "=", "+=", "-=", "*=", "/=", "%=", ")", ",", "]" };
        Selectionset.follow_INCORDECOPT = new String[] { "*", "/", "%", "+", "-", "<", ">", "==", "!=", "<=", ">=", "&", "|", "}", ";", "=", "+=", "-=", "*=", "/=", "%=", ")", ",", "]" };
        Selectionset.follow_IDOPT = new String[] { ")" };
        Selectionset.follow_DOT = new String[] { "*", "/", "%", "+", "-", "<", ">", "==", "!=", "<=", ">=", "&", "|", "(", "++", "--", "}", ";", "=", "+=", "-=", "*=", "/=", "%=", ")", ",", "]" };
        Selectionset.follow_C2 = new String[] { ";" };
        Selectionset.follow_PARAMINIT = new String[] { ")" };
        Selectionset.follow_F1 = new String[] { "*", "/", "%", "+", "-", "<", ">", "==", "!=", "<=", ">=", "&", "|", "}", ";", "=", "+=", "-=", "*=", "/=", "%=", ")", ",", "]" };
        Selectionset.follow_IDM = new String[] { "*", "/", "%", "+", "-", "<", ">", "==", "!=", "<=", ">=", "&", "|", "(", "++", "--", "}", ";", "=", "+=", "-=", "*=", "/=", "%=", ")", ",", "]" };
        Selectionset.follow_ID1 = new String[] { "*", "/", "%", "+", "-", "<", ">", "==", "!=", "<=", ">=", "&", "|", "(", "++", "--", "}", ";", "=", "+=", "-=", "*=", "/=", "%=", ")", ",", "]" };
    }
}